[pytest]
asyncio_mode = auto
filterwarnings =
    error::DeprecationWarning:custom_components.severn_trent.*
    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning
